### ISSUE TITLE
Throws Exception while running the script .. Need FIX 

### ISSUE THREAD

**Issue by droidmanspace** [robaleman/discord-cryptocurrency-bot#1]
Error :
```
                      if (err) throw err;
                               ^
Error in R script ta-tools/ichimoku.R
 'missing value where TRUE/FALSE needed'
```

**Comment by robaleman** [comment]
Thanks for the error report. The r-script can be buggy and sometimes has trouble parsing the JSON and ends up passing either an incomplete or null object through to R. I'll be debugging and pushing more updates over the next couple days to fix these errors.

EDIT: Switching to the bug-fixed fork of r-script helped!
https://www.npmjs.com/package/r-script-with-bug-fixes
