### ISSUE TITLE
Ichimoku not working

### ISSUE THREAD

**Issue by wereii** [robaleman/discord-cryptocurrency-bot#3]
![image](https://user-images.githubusercontent.com/8504482/39401608-6f90f432-4b49-11e8-83c8-efa285fcdf71.png)

- centos 7 
- Node v6.14.0 (from epel repo)
- npm v3.10.10

Everything else is working.

**Comment by robaleman** [comment]
Thanks for the heads up! Looks like another bug with the R-Script module that has popped up a couple weeks ago. Someone already found a fix so replacing these two lines of code in the main file of R-Script will fix your error.
https://github.com/joshkatz/r-script/pull/20
https://github.com/joshkatz/r-script/issues/19

Will be updating the repo to use the newest R-Script fork shortly.
